trigger:
  branches:
    include:
    - Master

variables:
  - group: Tenable.io
  - name: Parameters.solution
    value: '**/Website/SourceCode/Profiles/Profiles.sln'
  - name: buildPlatform
    value: "Any CPU"
  - name: buildConfiguration
    value:  'Release'
  - name: Parameters.Websitename
    value:  'ProfilesRNS'
  - name: Parameters.Artifactname
    value:  'ProfilesRNS_Drop'
  - name: Parameters.Contents
    value: '**/Website/SourceCode/Profiles/Profiles/web.**.config'
  - name: Parameters.packagetype 
    value: '*.zip'
  - name: Parameters.VirtualApplication
    value: 'Profiles'
  - name: Parameters.WebsitePhysicalPath
    value: 'E:\WebContent\ProfilesRNS'
  - name: Parameters.msbuildArgs
    value:  '/t:rebuild /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:PackageLocation="$(Build.ArtifactStagingDirectory)\build"'



stages:
- stage: Build_Application
  jobs:
  - job: Build
    pool:
      name: Azure Pipelines
      vmImage: windows-latest
      demands:
      - msbuild
      - visualstudio
      - vstest
    steps:

    - task: NuGetToolInstaller@0
      displayName: Use NuGet 6.6.1
      inputs:
        versionSpec: 6.6.1
    - task: NuGetCommand@2
      displayName: NuGet restore
      inputs:
        command: 'restore'
        restoreSolution: '$(Parameters.solution)'
        feedsToUse: 'config'

    - task: VSBuild@1
      displayName: Build solution
      inputs:
        solution: $(Parameters.solution)
        platform: $(BuildPlatform)
        configuration: $(BuildConfiguration)
        msbuildArgs: $(Parameters.msbuildArgs)

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)/build/TransformConfig'
      inputs:
        SourceFolder: $(Build.Repository.LocalPath)
        TargetFolder: $(Build.ArtifactStagingDirectory)/build/TransformConfig
        Contents: $(Parameters.Contents)
        flattenFolders: true

    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact
      inputs:
        PathtoPublish: $(build.artifactstagingdirectory)/build/Profiles.zip
        ArtifactName: $(Parameters.ArtifactName)
      condition: succeededOrFailed()

    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact
      inputs:
        PathtoPublish: $(build.artifactstagingdirectory)/build/TransformConfig
        ArtifactName: $(Parameters.ArtifactName)
      condition: succeededOrFailed()

- stage: Test_Deploy
  jobs:
  - deployment: DeployProfiles_Test
    displayName: DeployProfiles_Test
    continueOnError: true
    timeoutInMinutes: 10
    variables:
        GoogleMapsKey: "$(GoogleMapskey_Value)"
        ProfilesDB: "$(ProfilesDB_Test)"

    environment: 
        name: Test
        resourceType: VirtualMachine
        tags: Profiles_Test_Terraform
        # Tags needs to be updated per Pipeline
    strategy: 
        runOnce:
          deploy:
            steps:

             - task: IISWebAppManagementOnMachineGroup@0
               displayName: 'Stop Profiles AppPool'
               inputs:
                 IISDeploymentType: 'IISApplicationPool'
                 ActionIISApplicationPool: 'StopAppPool'
                 StartStopRecycleAppPoolName: 'ProfilesRNS'
             - task: IISWebAppDeploymentOnMachineGroup@0
               displayName: 'IIS Web site Deploy'
               inputs:
                 WebSiteName: '$(Parameters.Websitename)'
                 Package: '$(Build.ArtifactStagingDirectory)/../$(Parameters.ArtifactName)/$(Parameters.packagetype)'
                 RemoveAdditionalFilesFlag: true
                 XmlVariableSubstitution: true

             - task: CopyFiles@1
               inputs:
                SourceFolder: '$(Build.ArtifactStagingDirectory)/../$(Parameters.ArtifactName)'
                Contents: 'web.Test.config'
                 #need update once the web.test.config file is created.
                TargetFolder: '$(Parameters.WebsitePhysicalPath)'

             - task: AzureKeyVault@1
               inputs:
                 azureSubscription: 'Azure-Production' # Replace with your service connection
                 KeyVaultName: 'umwazkvprofilesshared'
                 SecretsFilter: 'ORCIDClientID, ORCIDClientSecret, GoogleMapsKey'
                 RunAsPreJob: false

             - powershell: |
                $configFile = "$(Parameters.WebsitePhysicalPath)\web.Test.config" 
                (Get-Content $configFile) -replace '__ORCIDClientID__', "$(ORCIDClientID)" | Set-Content $configFile
                (Get-Content $configFile) -replace '__ORCIDClientSecret__', "$(ORCIDClientSecret)" | Set-Content $configFile
                (Get-Content $configFile) -replace '__GoogleMapsKey__', "$(GoogleMapsKey)" | Set-Content $configFile
               displayName: 'Replace Tokens in web.config'

             - task: FileTransform@1
               inputs:
                folderPath: '$(Parameters.WebsitePhysicalPath)'
                #FolderPath is pipeline specific
                enableXmlTransform: true
                xmlTransformationRules: '-transform web.Test.config -xml web.config'

             - task: IISWebAppManagementOnMachineGroup@0
               displayName: 'Start Profiles AppPool'
               inputs:
                IISDeploymentType: 'IISApplicationPool'
                ActionIISApplicationPool: 'StartAppPool'
                StartStopRecycleAppPoolName: 'ProfilesRNS'

             - task: DeleteFiles@1
               inputs:
                SourceFolder: '$(Build.ArtifactStagingDirectory)/../$(Parameters.ArtifactName)'
                Contents: $(Parameters.packagetype)

- stage: Test_Tenable_io
  jobs:
    - job: Tenable_io_Scan_TestEnv
      pool:
        name: Azure Pipelines
        vmImage: windows-latest
      displayName: 'Launch Tenable.io Scan for ProfilesRNS NonProd Website'
      steps:
             - task: PowerShell@2
               #displayName: Launch Tenable.io
               inputs:
                 targetType: 'inline'
                 script: |
                   $headers=@{}
                   $headers.Add("accept", "application/json")
                   $headers.Add("X-ApiKeys", "accessKey=$(Tenable.accessKey);secretKey=$(Tenable.secretKey)")
                   $response = Invoke-WebRequest -Uri 'https://cloud.tenable.com/was/v2/configs/77cbe739-9f52-4ddf-8cda-ea71c67280a8/scans' -Method POST -Headers $headers



- stage: Prod_Deploy
  jobs:
  - deployment: DeployProfiles_Prod
    displayName: DeployProfiles_Prod
    continueOnError: true
    timeoutInMinutes: 10
    variables:
        GoogleMapsKey: "$(GoogleMapskey_Value)"
        ProfilesDB: "$(ProfilesDB_Prod)"

    environment: 
        name: Production
        resourceType: VirtualMachine
        tags: Profiles_Prod_Terraform
        # Tags needs to be updated per Pipeline
    strategy: 
        runOnce:
          deploy:
            steps:

             - task: IISWebAppManagementOnMachineGroup@0
               displayName: 'Stop Profiles AppPool'
               inputs:
                 IISDeploymentType: 'IISApplicationPool'
                 ActionIISApplicationPool: 'StopAppPool'
                 StartStopRecycleAppPoolName: 'ProfilesRNS'
             - task: IISWebAppDeploymentOnMachineGroup@0
               displayName: 'IIS Web site Deploy'
               inputs:
                 WebSiteName: '$(Parameters.Websitename)'
                 Package: '$(Build.ArtifactStagingDirectory)/../$(Parameters.ArtifactName)/$(Parameters.packagetype)'
                 RemoveAdditionalFilesFlag: true
                 XmlVariableSubstitution: true

             - task: CopyFiles@1
               inputs:
                SourceFolder: '$(Build.ArtifactStagingDirectory)/../$(Parameters.ArtifactName)'
                Contents: 'web.Prod.config'
                TargetFolder: '$(Parameters.WebsitePhysicalPath)'

             - task: AzureKeyVault@1
               inputs:
                 azureSubscription: 'Azure-Production' # Replace with your service connection
                 KeyVaultName: 'umwazkvprofilesshared'
                 SecretsFilter: 'ORCIDClientID, ORCIDClientSecret, GoogleMapsKey'
                 RunAsPreJob: false

             - powershell: |
                $configFile = "$(Parameters.WebsitePhysicalPath)\web.Prod.config" 
                (Get-Content $configFile) -replace '__ORCIDClientID__', "$(ORCIDClientID)" | Set-Content $configFile
                (Get-Content $configFile) -replace '__ORCIDClientSecret__', "$(ORCIDClientSecret)" | Set-Content $configFile
                (Get-Content $configFile) -replace '__GoogleMapsKey__', "$(GoogleMapsKey)" | Set-Content $configFile
               displayName: 'Replace Tokens in web.config'

             - task: FileTransform@1
               inputs:
                folderPath: '$(Parameters.WebsitePhysicalPath)'
                #FolderPath is pipeline specific
                enableXmlTransform: true
                xmlTransformationRules: '-transform web.Prod.config -xml web.config'

             - task: IISWebAppManagementOnMachineGroup@0
               displayName: 'Start Profiles AppPool'
               inputs:
                IISDeploymentType: 'IISApplicationPool'
                ActionIISApplicationPool: 'StartAppPool'
                StartStopRecycleAppPoolName: 'ProfilesRNS'

             - task: DeleteFiles@1
               inputs:
                SourceFolder: '$(Build.ArtifactStagingDirectory)/../$(Parameters.ArtifactName)'
                Contents: $(Parameters.packagetype)

